server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true



  security:
    user:
      name: user
      password: 123
      
keycloak:
  auth-server-url: https://52.205.251.144:8443
