
spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/springBootAppReaml/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/springBootAppReaml

