server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: springboot
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true



  security:
    user:
      name: user
      password: 123
      
keycloak:
  auth-server-url: https://localhost:8443
